# Generated by Django 5.1.2 on 2024-10-25 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Antal'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Varans namn'),
        ),
        migrations.CreateModel(
            name='SharedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listor.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_shared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
